version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /images/proxy
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /images/agent
    schedule:
      interval: weekly
